#!/usr/bin/env bash
# https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail
set -Eeuo pipefail
# cd to script location
cd "$(dirname "${BASH_SOURCE[0]}")"


# get total duration
total_duration=$(cat "$HOME/.wpfr/total-duration")

# get current position
current_position=$(cat "$HOME/.wpfr/current-position")

# echo "total_duration: $total_duration"
# echo "current_position: $current_position"

# determine video and relative position
# iterate over all videos
cumulative_duration=0
for video in "$HOME/.wpfr/videos/duration/"*; do
    # get filename
    filename=$(basename "$video")
    # get duration
    duration=$(cat "$video")
    # add duration to cumulative duration
    cumulative_duration=$(echo "$cumulative_duration + $duration" | bc)

    # if cumulative duration is greater than current position
    if (( $(echo "$cumulative_duration > $current_position" | bc -l) )); then
        # set video and relative position
        selected_video=$(cat "$HOME/.wpfr/videos/path/$filename")
        relative_position=$(echo "$current_position - ($cumulative_duration - $duration)" | bc)
        break
    fi
done

echo "selected_video: $selected_video"
echo "$selected_video" > "$HOME/.wpfr/current-video"
echo "$relative_position" > "$HOME/.wpfr/current-relative-position"

# unique filename to avoid concurrent writes of different instances to the same file


screenshot() (
  videofile="$1"
  time="$2"
  targetfile="$3"

  mpvsocket=$(mktemp --suffix="_mpv_ipc")

  # only mpv
  # mpv -wid 0  --really-quiet --input-ipc-server="$mpvsocket" --no-audio --no-sub --start="$time" --frames=1 --no-osc --no-osd-bar --osd-level=0 --pause --screenshot-jpeg-quality=100 "$videofile" &

  # xwinwrap in little window
  #  
  xwinwrap -ov -g 32x24+50+50 -- mpv -wid WID --really-quiet --input-ipc-server="$mpvsocket" --hwdec=no --no-audio --no-sub --start="$time" --frames=1 --no-osc --no-osd-bar --osd-level=0 --pause --screenshot-jpeg-quality=100 -- "$videofile" &

  # xwinwrap fullscreen
  # xwinwrap -ov -fs -- mpv -wid WID  --really-quiet --input-ipc-server="$mpvsocket" --no-audio --no-sub --start="$time" --frames=1 --no-osc --no-osd-bar --osd-level=0 --pause --screenshot-jpeg-quality=100 "$videofile" &

  # get pid
  mpvpid=$!

  # wait until mpv is ready to accept commands
  until echo '{ "command": ["get_property", "seeking"] }' | socat - "$mpvsocket" | grep -q "false"; do
    echo "waiting for mpv to become ready..."
    sleep 0.1
  done


  echo "taking screenshot..."
  rm -f "$targetfile"
  echo "screenshot-to-file $targetfile" | socat - "$mpvsocket"

  # quit mpv
  echo '{ "command": ["quit"] }' | socat - "$mpvsocket"

  # wait until file appears
  while [ ! -f "$targetfile" ]; do
    sleep 0.5
  done

  convert -trim "$targetfile" "$targetfile"

  echo "screenshot taken"

  # wait for all background jobs to finish
  wait
  rm -f "$mpvsocket"
)


# screenshot2() (
#   videofile="$1"
#   time="$2"
#   targetfile="$3"

#   # extract frame from video
#   mpv --vo=image --vo-image-outdir=/tmp --vo-image-jpeg-quality=100 --start="$time" --frames=1 --no-osc --no-osd-bar --osd-level=0 "$videofile"
#   mv "/tmp/00000001.jpg" "$targetfile"
# )

time screenshot "$selected_video" "$relative_position" "$HOME/.wpfr/current-frame.jpg"
