#!/usr/bin/env bash
# https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail
set -Eeuo pipefail
# cd to script location
cd "$(dirname "${BASH_SOURCE[0]}")"

VIDEO=$(cat "$HOME/.wpfr/current-video")
POSITION=$(cat "$HOME/.wpfr/current-position")

mkdir -p $HOME/.wpfr/saved
cp "$HOME/.wpfr/current-frame.jpg" "$HOME/.wpfr/saved/$(basename "$VIDEO")-$POSITION.jpg"
