#!/usr/bin/env bash
# https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail
set -Eeuo pipefail
# cd to script location
cd "$(dirname "${BASH_SOURCE[0]}")"


DELTA=${1:-1}


# read position from file, in home folder
POSITION=$(cat "$HOME/.wpfr/current-position")

# increase position by delta
POSITION=$(echo "$POSITION + $DELTA" | bc)

# write position to file, in home folder
echo "$POSITION" > "$HOME/.wpfr/current-position"

./kill-video
./extract-frame
./set-wallpaper


