#!/usr/bin/env bash
# https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail
set -Eeuo pipefail
# cd to script location
cd "$(dirname "${BASH_SOURCE[0]}")"

echo "setting wallpaper..."

# set as wallpaper
feh --bg-fill $HOME/.wpfr/current-frame.jpg
